### ISSUE TITLE
requirements.txt file not found

### ISSUE THREAD

**Issue by BusiPlay** [LinkedInLearning/python-scientific-stack-3006561#1]
## Issue Overview
No Requirements.txt file in repo

## Describe your environment
MacOS environment, git repo cloned

## Steps to Reproduce

1. Clone this repository
2. cd into repo root
3. Per course instructions, execute python3 -m venv venv
4. Per course instructions and README, execute ./venv/bin/python -m pip install -r requirements.txt

## Expected Behavior
pip should install course wide requirements

## Current Behavior
command failed with following:
ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'

## Possible Solution
Either include requirements.txt file in repo root or remove specific command from README if this step is going to be done within individual exercise subfolders

**Comment by tebeka** [comment]
Thanks @BusiPlay! Fixed
